# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1561, 836)
        Form.setStyleSheet("#Form{\n"
"    background-color:white;\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-30, 0, 301, 838))
        self.label.setStyleSheet("background-color: rgb(0, 0, 235);\n"
"border:1px solid transparent;\n"
"border-radius:40px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.menu_acar_yarad = QtWidgets.QPushButton(Form)
        self.menu_acar_yarad.setGeometry(QtCore.QRect(10, 170, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.menu_acar_yarad.setFont(font)
        self.menu_acar_yarad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_acar_yarad.setAccessibleName("")
        self.menu_acar_yarad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_acar_yarad.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:transparent;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.2);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.3);\n"
"    \n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/gifler/key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_acar_yarad.setIcon(icon)
        self.menu_acar_yarad.setIconSize(QtCore.QSize(38, 38))
        self.menu_acar_yarad.setCheckable(True)
        self.menu_acar_yarad.setChecked(True)
        self.menu_acar_yarad.setAutoRepeat(False)
        self.menu_acar_yarad.setAutoExclusive(True)
        self.menu_acar_yarad.setObjectName("menu_acar_yarad")
        self.menu_logo_label = QtWidgets.QLabel(Form)
        self.menu_logo_label.setGeometry(QtCore.QRect(70, 20, 111, 111))
        self.menu_logo_label.setStyleSheet("")
        self.menu_logo_label.setText("")
        self.menu_logo_label.setPixmap(QtGui.QPixmap(":/newPrefix/gifler/logo.png"))
        self.menu_logo_label.setScaledContents(True)
        self.menu_logo_label.setObjectName("menu_logo_label")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(220, 0, 1341, 841))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setStyleSheet("background-color: rgb(248, 249, 253);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_metn = QtWidgets.QWidget()
        self.page_metn.setObjectName("page_metn")
        self.label_8 = QtWidgets.QLabel(self.page_metn)
        self.label_8.setGeometry(QtCore.QRect(110, 60, 1171, 711))
        self.label_8.setStyleSheet("background-color:white;\n"
"border:1px solid rgba(0,0,0,0.2);\n"
"border-radius:45px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.metn_sfirele_plaintext = QtWidgets.QPlainTextEdit(self.page_metn)
        self.metn_sfirele_plaintext.setGeometry(QtCore.QRect(220, 240, 951, 341))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.metn_sfirele_plaintext.setFont(font)
        self.metn_sfirele_plaintext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.metn_sfirele_plaintext.setStyleSheet("QPlainTextEdit{\n"
"    border:1px solid black;\n"
"    border-radius:15px;\n"
"    text-align:center;\n"
"}")
        self.metn_sfirele_plaintext.setObjectName("metn_sfirele_plaintext")
        self.metn_sfirele_kopyala_btn = QtWidgets.QPushButton(self.page_metn)
        self.metn_sfirele_kopyala_btn.setGeometry(QtCore.QRect(370, 610, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.metn_sfirele_kopyala_btn.setFont(font)
        self.metn_sfirele_kopyala_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.metn_sfirele_kopyala_btn.setAccessibleName("")
        self.metn_sfirele_kopyala_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.metn_sfirele_kopyala_btn.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgb(0,0,235);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255,0.9);\n"
"    \n"
"}\n"
"")
        self.metn_sfirele_kopyala_btn.setCheckable(True)
        self.metn_sfirele_kopyala_btn.setChecked(True)
        self.metn_sfirele_kopyala_btn.setAutoRepeat(False)
        self.metn_sfirele_kopyala_btn.setAutoExclusive(True)
        self.metn_sfirele_kopyala_btn.setObjectName("metn_sfirele_kopyala_btn")
        self.label_9 = QtWidgets.QLabel(self.page_metn)
        self.label_9.setGeometry(QtCore.QRect(250, 180, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setMouseTracking(False)
        self.label_9.setStyleSheet("color: rgb(0, 0, 235);\n"
"border:1px solid rgba(0,0,0,0.2);\n"
"border-radius: 20px;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.metn_sifrele_baslat_btn = QtWidgets.QPushButton(self.page_metn)
        self.metn_sifrele_baslat_btn.setGeometry(QtCore.QRect(610, 610, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.metn_sifrele_baslat_btn.setFont(font)
        self.metn_sifrele_baslat_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.metn_sifrele_baslat_btn.setAccessibleName("")
        self.metn_sifrele_baslat_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.metn_sifrele_baslat_btn.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgb(0,0,235);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255,0.9);\n"
"    \n"
"}\n"
"")
        self.metn_sifrele_baslat_btn.setCheckable(True)
        self.metn_sifrele_baslat_btn.setChecked(True)
        self.metn_sifrele_baslat_btn.setAutoRepeat(False)
        self.metn_sifrele_baslat_btn.setAutoExclusive(True)
        self.metn_sifrele_baslat_btn.setObjectName("metn_sifrele_baslat_btn")
        self.metn_sifrele_combobox = QtWidgets.QComboBox(self.page_metn)
        self.metn_sifrele_combobox.setGeometry(QtCore.QRect(920, 180, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.metn_sifrele_combobox.setFont(font)
        self.metn_sifrele_combobox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.metn_sifrele_combobox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.metn_sifrele_combobox.setStyleSheet("color: rgb(0, 0, 235);\n"
"border:1px solid rgba(0,0,0,0.2);\n"
"border-radius: 20px;")
        self.metn_sifrele_combobox.setObjectName("metn_sifrele_combobox")
        self.metn_sifrele_combobox.addItem("")
        self.metn_sifrele_combobox.addItem("")
        self.metn_sifrele_sifirla_btn = QtWidgets.QPushButton(self.page_metn)
        self.metn_sifrele_sifirla_btn.setGeometry(QtCore.QRect(850, 610, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.metn_sifrele_sifirla_btn.setFont(font)
        self.metn_sifrele_sifirla_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.metn_sifrele_sifirla_btn.setAccessibleName("")
        self.metn_sifrele_sifirla_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.metn_sifrele_sifirla_btn.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgb(0,0,235);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255,0.9);\n"
"    \n"
"}\n"
"")
        self.metn_sifrele_sifirla_btn.setCheckable(True)
        self.metn_sifrele_sifirla_btn.setChecked(True)
        self.metn_sifrele_sifirla_btn.setAutoRepeat(False)
        self.metn_sifrele_sifirla_btn.setAutoExclusive(True)
        self.metn_sifrele_sifirla_btn.setObjectName("metn_sifrele_sifirla_btn")
        self.stackedWidget.addWidget(self.page_metn)
        self.page_qovluq = QtWidgets.QWidget()
        self.page_qovluq.setObjectName("page_qovluq")
        self.qovluq_sifrele_combobox = QtWidgets.QComboBox(self.page_qovluq)
        self.qovluq_sifrele_combobox.setGeometry(QtCore.QRect(480, 580, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.qovluq_sifrele_combobox.setFont(font)
        self.qovluq_sifrele_combobox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qovluq_sifrele_combobox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qovluq_sifrele_combobox.setStyleSheet("color: rgb(0, 0, 235);\n"
"border:1px solid rgba(0,0,0,0.2);\n"
"border-radius: 20px;")
        self.qovluq_sifrele_combobox.setObjectName("qovluq_sifrele_combobox")
        self.qovluq_sifrele_combobox.addItem("")
        self.qovluq_sifrele_combobox.addItem("")
        self.label_17 = QtWidgets.QLabel(self.page_qovluq)
        self.label_17.setGeometry(QtCore.QRect(350, 160, 641, 211))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(0, 0, 235);\n"
"border:1px solid rgba(0,0,255,0.8);\n"
"border-radius: 20px;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_qovluq)
        self.label_18.setGeometry(QtCore.QRect(110, 60, 1171, 711))
        self.label_18.setStyleSheet("background-color:white;\n"
"border:1px solid rgba(0,0,0,0.2);\n"
"border-radius:45px;")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.qovluq_sifrele_baslat = QtWidgets.QPushButton(self.page_qovluq)
        self.qovluq_sifrele_baslat.setGeometry(QtCore.QRect(700, 580, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.qovluq_sifrele_baslat.setFont(font)
        self.qovluq_sifrele_baslat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qovluq_sifrele_baslat.setAccessibleName("")
        self.qovluq_sifrele_baslat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qovluq_sifrele_baslat.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgb(0,0,235);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255,0.9);\n"
"    \n"
"}\n"
"")
        self.qovluq_sifrele_baslat.setCheckable(True)
        self.qovluq_sifrele_baslat.setChecked(True)
        self.qovluq_sifrele_baslat.setAutoRepeat(False)
        self.qovluq_sifrele_baslat.setAutoExclusive(True)
        self.qovluq_sifrele_baslat.setObjectName("qovluq_sifrele_baslat")
        self.qovluq_sec_btn = QtWidgets.QPushButton(self.page_qovluq)
        self.qovluq_sec_btn.setGeometry(QtCore.QRect(910, 470, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.qovluq_sec_btn.setFont(font)
        self.qovluq_sec_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qovluq_sec_btn.setAccessibleName("")
        self.qovluq_sec_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qovluq_sec_btn.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgb(0,0,235);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255,0.9);\n"
"    \n"
"}\n"
"")
        self.qovluq_sec_btn.setCheckable(True)
        self.qovluq_sec_btn.setChecked(True)
        self.qovluq_sec_btn.setAutoRepeat(False)
        self.qovluq_sec_btn.setAutoExclusive(True)
        self.qovluq_sec_btn.setObjectName("qovluq_sec_btn")
        self.qovluq_path_lineedit = QtWidgets.QLineEdit(self.page_qovluq)
        self.qovluq_path_lineedit.setGeometry(QtCore.QRect(280, 470, 611, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        self.qovluq_path_lineedit.setFont(font)
        self.qovluq_path_lineedit.setStyleSheet("border:1px solid rgba(0,0,0,0.6);\n"
"border-radius: 15px;\n"
"")
        self.qovluq_path_lineedit.setText("")
        self.qovluq_path_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.qovluq_path_lineedit.setObjectName("qovluq_path_lineedit")
        self.label_18.raise_()
        self.label_17.raise_()
        self.qovluq_sifrele_combobox.raise_()
        self.qovluq_sifrele_baslat.raise_()
        self.qovluq_sec_btn.raise_()
        self.qovluq_path_lineedit.raise_()
        self.stackedWidget.addWidget(self.page_qovluq)
        self.page_haqqinda = QtWidgets.QWidget()
        self.page_haqqinda.setObjectName("page_haqqinda")
        self.label_19 = QtWidgets.QLabel(self.page_haqqinda)
        self.label_19.setGeometry(QtCore.QRect(80, 60, 1251, 751))
        self.label_19.setStyleSheet("background-color:white;\n"
"border:1px solid rgba(0,0,0,0.2);\n"
"border-radius:45px;")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_haqqinda)
        self.label_20.setGeometry(QtCore.QRect(120, 160, 1171, 631))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(0, 0, 235);\n"
"border:1px solid rgba(0,0,255,0.8);\n"
"border-radius: 20px;")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_haqqinda)
        self.label_21.setGeometry(QtCore.QRect(120, 80, 581, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 0, 235);\n"
"border:1px solid rgba(0,0,255,0.8);\n"
"border-radius: 20px;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.developer_btn = QtWidgets.QPushButton(self.page_haqqinda)
        self.developer_btn.setGeometry(QtCore.QRect(720, 80, 581, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.developer_btn.setFont(font)
        self.developer_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.developer_btn.setAccessibleName("")
        self.developer_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.developer_btn.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgb(0,0,235);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255,0.9);\n"
"    \n"
"}\n"
"")
        self.developer_btn.setCheckable(True)
        self.developer_btn.setChecked(True)
        self.developer_btn.setAutoRepeat(False)
        self.developer_btn.setAutoExclusive(True)
        self.developer_btn.setObjectName("developer_btn")
        self.stackedWidget.addWidget(self.page_haqqinda)
        self.page_acar_yarat = QtWidgets.QWidget()
        self.page_acar_yarat.setObjectName("page_acar_yarat")
        self.label_3 = QtWidgets.QLabel(self.page_acar_yarat)
        self.label_3.setGeometry(QtCore.QRect(180, 60, 1031, 331))
        self.label_3.setStyleSheet("color:rgb(255,255,255);\n"
"border: 1px solid rgba(0,0,0,0.2);\n"
"border-radius:45px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.yeni_acar_yarat_btn = QtWidgets.QPushButton(self.page_acar_yarat)
        self.yeni_acar_yarat_btn.setGeometry(QtCore.QRect(490, 280, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.yeni_acar_yarat_btn.setFont(font)
        self.yeni_acar_yarat_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.yeni_acar_yarat_btn.setAccessibleName("")
        self.yeni_acar_yarat_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yeni_acar_yarat_btn.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgb(0,0,235);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255,0.9);\n"
"    \n"
"}\n"
"")
        self.yeni_acar_yarat_btn.setCheckable(True)
        self.yeni_acar_yarat_btn.setChecked(True)
        self.yeni_acar_yarat_btn.setAutoRepeat(False)
        self.yeni_acar_yarat_btn.setAutoExclusive(True)
        self.yeni_acar_yarat_btn.setObjectName("yeni_acar_yarat_btn")
        self.yaradilmis_acar_lineedit = QtWidgets.QLineEdit(self.page_acar_yarat)
        self.yaradilmis_acar_lineedit.setGeometry(QtCore.QRect(200, 160, 891, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yaradilmis_acar_lineedit.setFont(font)
        self.yaradilmis_acar_lineedit.setStyleSheet("QLineEdit{\n"
"    border:1px solid rgba(0,0,0,0.3);\n"
"    border-radius:20px;\n"
"}")
        self.yaradilmis_acar_lineedit.setText("")
        self.yaradilmis_acar_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.yaradilmis_acar_lineedit.setDragEnabled(True)
        self.yaradilmis_acar_lineedit.setReadOnly(True)
        self.yaradilmis_acar_lineedit.setClearButtonEnabled(False)
        self.yaradilmis_acar_lineedit.setObjectName("yaradilmis_acar_lineedit")
        self.kopyala_movie = QtWidgets.QLabel(self.page_acar_yarat)
        self.kopyala_movie.setGeometry(QtCore.QRect(1110, 150, 61, 61))
        self.kopyala_movie.setMouseTracking(True)
        self.kopyala_movie.setObjectName("kopyala_movie")
        self.yadda_saxla_btn = QtWidgets.QPushButton(self.page_acar_yarat)
        self.yadda_saxla_btn.setGeometry(QtCore.QRect(490, 650, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.yadda_saxla_btn.setFont(font)
        self.yadda_saxla_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.yadda_saxla_btn.setAccessibleName("")
        self.yadda_saxla_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yadda_saxla_btn.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgb(0,0,235);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(0, 0, 255,0.9);\n"
"    \n"
"}\n"
"")
        self.yadda_saxla_btn.setCheckable(True)
        self.yadda_saxla_btn.setChecked(True)
        self.yadda_saxla_btn.setAutoRepeat(False)
        self.yadda_saxla_btn.setAutoExclusive(True)
        self.yadda_saxla_btn.setObjectName("yadda_saxla_btn")
        self.acari_daxil_et_lineedit = QtWidgets.QLineEdit(self.page_acar_yarat)
        self.acari_daxil_et_lineedit.setGeometry(QtCore.QRect(260, 530, 891, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.acari_daxil_et_lineedit.setFont(font)
        self.acari_daxil_et_lineedit.setStyleSheet("QLineEdit{\n"
"    border:1px solid rgba(0,0,0,0.3);\n"
"    border-radius:20px;\n"
"}")
        self.acari_daxil_et_lineedit.setText("")
        self.acari_daxil_et_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.acari_daxil_et_lineedit.setDragEnabled(True)
        self.acari_daxil_et_lineedit.setReadOnly(False)
        self.acari_daxil_et_lineedit.setClearButtonEnabled(True)
        self.acari_daxil_et_lineedit.setObjectName("acari_daxil_et_btn")
        self.label_5 = QtWidgets.QLabel(self.page_acar_yarat)
        self.label_5.setGeometry(QtCore.QRect(180, 430, 1031, 331))
        self.label_5.setStyleSheet("color:rgb(255,255,255);\n"
"border: 1px solid rgba(0,0,0,0.2);\n"
"border-radius:45px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_acar_yarat)
        self.label_6.setGeometry(QtCore.QRect(210, 90, 971, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 235);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_acar_yarat)
        self.label_7.setGeometry(QtCore.QRect(210, 460, 971, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("color: rgb(0, 0, 235);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_3.raise_()
        self.yeni_acar_yarat_btn.raise_()
        self.yaradilmis_acar_lineedit.raise_()
        self.kopyala_movie.raise_()
        self.label_5.raise_()
        self.acari_daxil_et_lineedit.raise_()
        self.yadda_saxla_btn.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.stackedWidget.addWidget(self.page_acar_yarat)
        self.menu_metn_sifr = QtWidgets.QPushButton(Form)
        self.menu_metn_sifr.setGeometry(QtCore.QRect(10, 250, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.menu_metn_sifr.setFont(font)
        self.menu_metn_sifr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_metn_sifr.setAccessibleName("")
        self.menu_metn_sifr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_metn_sifr.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:transparent;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.2);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.3);\n"
"    \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/gifler/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_metn_sifr.setIcon(icon1)
        self.menu_metn_sifr.setIconSize(QtCore.QSize(40, 40))
        self.menu_metn_sifr.setCheckable(True)
        self.menu_metn_sifr.setChecked(True)
        self.menu_metn_sifr.setAutoRepeat(False)
        self.menu_metn_sifr.setAutoExclusive(True)
        self.menu_metn_sifr.setObjectName("menu_metn_sifr")
        self.menu_qovluq_sifr = QtWidgets.QPushButton(Form)
        self.menu_qovluq_sifr.setGeometry(QtCore.QRect(10, 330, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.menu_qovluq_sifr.setFont(font)
        self.menu_qovluq_sifr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_qovluq_sifr.setAccessibleName("")
        self.menu_qovluq_sifr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_qovluq_sifr.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:transparent;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.2);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.3);\n"
"    \n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/gifler/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_qovluq_sifr.setIcon(icon2)
        self.menu_qovluq_sifr.setIconSize(QtCore.QSize(40, 40))
        self.menu_qovluq_sifr.setCheckable(True)
        self.menu_qovluq_sifr.setChecked(True)
        self.menu_qovluq_sifr.setAutoRepeat(False)
        self.menu_qovluq_sifr.setAutoExclusive(True)
        self.menu_qovluq_sifr.setObjectName("menu_qovluq_sifr")
        self.menu_haqqinda = QtWidgets.QPushButton(Form)
        self.menu_haqqinda.setGeometry(QtCore.QRect(10, 710, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.menu_haqqinda.setFont(font)
        self.menu_haqqinda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_haqqinda.setAccessibleName("")
        self.menu_haqqinda.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_haqqinda.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:transparent;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.2);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.3);\n"
"    \n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/gifler/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_haqqinda.setIcon(icon3)
        self.menu_haqqinda.setIconSize(QtCore.QSize(30, 35))
        self.menu_haqqinda.setCheckable(True)
        self.menu_haqqinda.setChecked(True)
        self.menu_haqqinda.setAutoRepeat(False)
        self.menu_haqqinda.setAutoExclusive(True)
        self.menu_haqqinda.setObjectName("menu_haqqinda")
        self.menu_cixis = QtWidgets.QPushButton(Form)
        self.menu_cixis.setGeometry(QtCore.QRect(10, 770, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.menu_cixis.setFont(font)
        self.menu_cixis.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_cixis.setAccessibleName("")
        self.menu_cixis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_cixis.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:transparent;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.2);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color: rgba(255, 255, 255,0.3);\n"
"    \n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/gifler/cixis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_cixis.setIcon(icon4)
        self.menu_cixis.setIconSize(QtCore.QSize(30, 30))
        self.menu_cixis.setCheckable(True)
        self.menu_cixis.setChecked(True)
        self.menu_cixis.setAutoRepeat(False)
        self.menu_cixis.setAutoExclusive(True)
        self.menu_cixis.setObjectName("menu_cixis")
        self.stackedWidget.raise_()
        self.label.raise_()
        self.menu_acar_yarad.raise_()
        self.menu_logo_label.raise_()
        self.menu_metn_sifr.raise_()
        self.menu_qovluq_sifr.raise_()
        self.menu_haqqinda.raise_()
        self.menu_cixis.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.menu_acar_yarad.setText(_translate("Form", "AES açarı yaradın"))
        self.metn_sfirele_kopyala_btn.setText(_translate("Form", "Kopyala"))
        self.label_9.setText(_translate("Form", "Mətni daxil edin"))
        self.metn_sifrele_baslat_btn.setText(_translate("Form", "Başlat"))
        self.metn_sifrele_combobox.setCurrentText(_translate("Form", "Şifrələmə"))
        self.metn_sifrele_combobox.setItemText(0, _translate("Form", "Şifrələmə"))
        self.metn_sifrele_combobox.setItemText(1, _translate("Form", "Deşifrələmə"))
        self.metn_sifrele_sifirla_btn.setText(_translate("Form", "Sıfırla"))
        self.qovluq_sifrele_combobox.setCurrentText(_translate("Form", "Şifrələmə"))
        self.qovluq_sifrele_combobox.setItemText(0, _translate("Form", "Şifrələmə"))
        self.qovluq_sifrele_combobox.setItemText(1, _translate("Form", "Deşifrələmə"))
        self.label_17.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_17.setText(_translate("Form", "Şifrələnəcək qovluğun tam yolunu daxil edin. Unutmayınki qovluqda olan hər bir fayl şifrələmə / deşifrələmə prosesindən keçəcəkdir. Proqram sistem fayllarına zərər gəlməsin deyə Əməliyyat Sisteminin yerləşdiyi fayllarda işləməyəcək!"))
        self.qovluq_sifrele_baslat.setText(_translate("Form", "Başlat"))
        self.qovluq_sec_btn.setText(_translate("Form", "Qovluq seç"))
        self.qovluq_path_lineedit.setPlaceholderText(_translate("Form", "Qovluğun yolun daxil edin vəya  >"))
        self.label_20.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_20.setText(_translate("Form", "- Gizlilik Siyasəti - \n"
"\n"
"Bu Gizlilik Siyasəti, tətbiqin gizlilik amillərini izah edir. Tətbiqimizi istifadə edərək, aşağıdakı siyasət və şərtləri qəbul etmiş sayılırsınız.\n"
"\n"
" - Topladığımız Məlumatlar - \n"
"\n"
"Şəxsi Məlumatlar : Tətbiq,istifadəçilərin şəxsi məlumatlarını toplamır və saxlamır.\n"
"\n"
"Şifrələmə Məlumatları : Tətbiq, istifadəçilərin istədikləri mətni və ya qovluğu AES şifrələməsini istifadə edərək qorumağa kömək edir. Bu şifrələməyə lazım olan məlumatlar, istifadəçi tərəfindən təyin edilmiş şifrə ilə yalnız istifadəçi tərəfindən əldə edilə bilər.\n"
"\n"
"- Məlumatların İstifadəsi -\n"
"\n"
"Tətbiq, istifadəçilərin təyin etdiyi mətni və ya qovluğu yalnız şifrələmək və istifadəçinin təyin etdiyi şifrə ilə açmaq məqsədiylə istifadə edir. Bu məlumatlar, istifadəçinin tələbi olmadan istifadə olunmur və paylaşılmır.\n"
"\n"
"- Üçüncü Tərəf Paylaşımı - \n"
"\n"
"Tətbiq, istifadəçi məlumatlarını üçüncü tərəflərlə paylaşmır və satmır.\n"
"\n"
"- Təhlükəsizlik - \n"
"\n"
"Tətbiq, istifadəçi məlumatlarının təhlükəsizliyini təmin etmək üçün AES kimi təhlükəsizlik tədbirlərindən istifadə edir."))
        self.label_21.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_21.setText(_translate("Form", "\" Encrypter-Aze \""))
        self.developer_btn.setText(_translate("Form", "Developer : Elmir Quliyev "))
        self.yeni_acar_yarat_btn.setText(_translate("Form", "Yeni açar yaradın"))
        self.yaradilmis_acar_lineedit.setPlaceholderText(_translate("Form", "                  Yaradılmış açar yoxdur."))
        self.kopyala_movie.setText(_translate("Form", "moive"))
        self.yadda_saxla_btn.setText(_translate("Form", "Yadda saxla"))
        self.acari_daxil_et_lineedit.setPlaceholderText(_translate("Form", " AES açarını daxil edin..."))
        self.label_6.setText(_translate("Form", "Açarı yaratdıqdan sonra aşağısındakı bölmədən yadda saxlamağı unutmayın!"))
        self.label_7.setText(_translate("Form", "Yadda saxlanılmış açar digər səhifələrdə şifrələmə üçün istifadə olunacaq."))
        self.menu_metn_sifr.setText(_translate("Form", "Mətn şifrələməsi"))
        self.menu_qovluq_sifr.setText(_translate("Form", "Qovluq şifrələmə"))
        self.menu_haqqinda.setText(_translate("Form", "Haqqında"))
        self.menu_cixis.setText(_translate("Form", "Çıxış    "))
import imgs_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
